/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as CorporaIndexRouteImport } from './routes/corpora/index';
import { Route as DocApiRouteImport } from './routes/doc/api';
import { Route as DocIdRouteImport } from './routes/doc/$id';
import { Route as CorporaCorpusIdIndexRouteImport } from './routes/corpora/$corpusId/index';
import { Route as CorporaCorpusIdTextIdRouteRouteImport } from './routes/corpora/$corpusId/$textId/route';
import { Route as CorporaCorpusIdTextIdIndexRouteImport } from './routes/corpora/$corpusId/$textId/index';
import { Route as CorporaCorpusIdTextIdPlantsRouteImport } from './routes/corpora/$corpusId/$textId/plants';
import { Route as CorporaCorpusIdTextIdFulltextRouteImport } from './routes/corpora/$corpusId/$textId/fulltext';
import { Route as CorporaCorpusIdTextIdEntitiesRouteImport } from './routes/corpora/$corpusId/$textId/entities';
import { Route as CorporaCorpusIdTextIdAnimalsRouteImport } from './routes/corpora/$corpusId/$textId/animals';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const CorporaIndexRoute = CorporaIndexRouteImport.update({
  id: '/corpora/',
  path: '/corpora/',
  getParentRoute: () => rootRouteImport,
} as any);
const DocApiRoute = DocApiRouteImport.update({
  id: '/doc/api',
  path: '/doc/api',
  getParentRoute: () => rootRouteImport,
} as any);
const DocIdRoute = DocIdRouteImport.update({
  id: '/doc/$id',
  path: '/doc/$id',
  getParentRoute: () => rootRouteImport,
} as any);
const CorporaCorpusIdIndexRoute = CorporaCorpusIdIndexRouteImport.update({
  id: '/corpora/$corpusId/',
  path: '/corpora/$corpusId/',
  getParentRoute: () => rootRouteImport,
} as any);
const CorporaCorpusIdTextIdRouteRoute =
  CorporaCorpusIdTextIdRouteRouteImport.update({
    id: '/corpora/$corpusId/$textId',
    path: '/corpora/$corpusId/$textId',
    getParentRoute: () => rootRouteImport,
  } as any);
const CorporaCorpusIdTextIdIndexRoute =
  CorporaCorpusIdTextIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CorporaCorpusIdTextIdRouteRoute,
  } as any);
const CorporaCorpusIdTextIdPlantsRoute =
  CorporaCorpusIdTextIdPlantsRouteImport.update({
    id: '/plants',
    path: '/plants',
    getParentRoute: () => CorporaCorpusIdTextIdRouteRoute,
  } as any);
const CorporaCorpusIdTextIdFulltextRoute =
  CorporaCorpusIdTextIdFulltextRouteImport.update({
    id: '/fulltext',
    path: '/fulltext',
    getParentRoute: () => CorporaCorpusIdTextIdRouteRoute,
  } as any);
const CorporaCorpusIdTextIdEntitiesRoute =
  CorporaCorpusIdTextIdEntitiesRouteImport.update({
    id: '/entities',
    path: '/entities',
    getParentRoute: () => CorporaCorpusIdTextIdRouteRoute,
  } as any);
const CorporaCorpusIdTextIdAnimalsRoute =
  CorporaCorpusIdTextIdAnimalsRouteImport.update({
    id: '/animals',
    path: '/animals',
    getParentRoute: () => CorporaCorpusIdTextIdRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/doc/$id': typeof DocIdRoute;
  '/doc/api': typeof DocApiRoute;
  '/corpora/': typeof CorporaIndexRoute;
  '/corpora/$corpusId/$textId': typeof CorporaCorpusIdTextIdRouteRouteWithChildren;
  '/corpora/$corpusId/': typeof CorporaCorpusIdIndexRoute;
  '/corpora/$corpusId/$textId/animals': typeof CorporaCorpusIdTextIdAnimalsRoute;
  '/corpora/$corpusId/$textId/entities': typeof CorporaCorpusIdTextIdEntitiesRoute;
  '/corpora/$corpusId/$textId/fulltext': typeof CorporaCorpusIdTextIdFulltextRoute;
  '/corpora/$corpusId/$textId/plants': typeof CorporaCorpusIdTextIdPlantsRoute;
  '/corpora/$corpusId/$textId/': typeof CorporaCorpusIdTextIdIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/doc/$id': typeof DocIdRoute;
  '/doc/api': typeof DocApiRoute;
  '/corpora': typeof CorporaIndexRoute;
  '/corpora/$corpusId': typeof CorporaCorpusIdIndexRoute;
  '/corpora/$corpusId/$textId/animals': typeof CorporaCorpusIdTextIdAnimalsRoute;
  '/corpora/$corpusId/$textId/entities': typeof CorporaCorpusIdTextIdEntitiesRoute;
  '/corpora/$corpusId/$textId/fulltext': typeof CorporaCorpusIdTextIdFulltextRoute;
  '/corpora/$corpusId/$textId/plants': typeof CorporaCorpusIdTextIdPlantsRoute;
  '/corpora/$corpusId/$textId': typeof CorporaCorpusIdTextIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/doc/$id': typeof DocIdRoute;
  '/doc/api': typeof DocApiRoute;
  '/corpora/': typeof CorporaIndexRoute;
  '/corpora/$corpusId/$textId': typeof CorporaCorpusIdTextIdRouteRouteWithChildren;
  '/corpora/$corpusId/': typeof CorporaCorpusIdIndexRoute;
  '/corpora/$corpusId/$textId/animals': typeof CorporaCorpusIdTextIdAnimalsRoute;
  '/corpora/$corpusId/$textId/entities': typeof CorporaCorpusIdTextIdEntitiesRoute;
  '/corpora/$corpusId/$textId/fulltext': typeof CorporaCorpusIdTextIdFulltextRoute;
  '/corpora/$corpusId/$textId/plants': typeof CorporaCorpusIdTextIdPlantsRoute;
  '/corpora/$corpusId/$textId/': typeof CorporaCorpusIdTextIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/doc/$id'
    | '/doc/api'
    | '/corpora/'
    | '/corpora/$corpusId/$textId'
    | '/corpora/$corpusId/'
    | '/corpora/$corpusId/$textId/animals'
    | '/corpora/$corpusId/$textId/entities'
    | '/corpora/$corpusId/$textId/fulltext'
    | '/corpora/$corpusId/$textId/plants'
    | '/corpora/$corpusId/$textId/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/doc/$id'
    | '/doc/api'
    | '/corpora'
    | '/corpora/$corpusId'
    | '/corpora/$corpusId/$textId/animals'
    | '/corpora/$corpusId/$textId/entities'
    | '/corpora/$corpusId/$textId/fulltext'
    | '/corpora/$corpusId/$textId/plants'
    | '/corpora/$corpusId/$textId';
  id:
    | '__root__'
    | '/'
    | '/doc/$id'
    | '/doc/api'
    | '/corpora/'
    | '/corpora/$corpusId/$textId'
    | '/corpora/$corpusId/'
    | '/corpora/$corpusId/$textId/animals'
    | '/corpora/$corpusId/$textId/entities'
    | '/corpora/$corpusId/$textId/fulltext'
    | '/corpora/$corpusId/$textId/plants'
    | '/corpora/$corpusId/$textId/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DocIdRoute: typeof DocIdRoute;
  DocApiRoute: typeof DocApiRoute;
  CorporaIndexRoute: typeof CorporaIndexRoute;
  CorporaCorpusIdTextIdRouteRoute: typeof CorporaCorpusIdTextIdRouteRouteWithChildren;
  CorporaCorpusIdIndexRoute: typeof CorporaCorpusIdIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/corpora/': {
      id: '/corpora/';
      path: '/corpora';
      fullPath: '/corpora/';
      preLoaderRoute: typeof CorporaIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/doc/api': {
      id: '/doc/api';
      path: '/doc/api';
      fullPath: '/doc/api';
      preLoaderRoute: typeof DocApiRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/doc/$id': {
      id: '/doc/$id';
      path: '/doc/$id';
      fullPath: '/doc/$id';
      preLoaderRoute: typeof DocIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/corpora/$corpusId/': {
      id: '/corpora/$corpusId/';
      path: '/corpora/$corpusId';
      fullPath: '/corpora/$corpusId/';
      preLoaderRoute: typeof CorporaCorpusIdIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/corpora/$corpusId/$textId': {
      id: '/corpora/$corpusId/$textId';
      path: '/corpora/$corpusId/$textId';
      fullPath: '/corpora/$corpusId/$textId';
      preLoaderRoute: typeof CorporaCorpusIdTextIdRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/corpora/$corpusId/$textId/': {
      id: '/corpora/$corpusId/$textId/';
      path: '/';
      fullPath: '/corpora/$corpusId/$textId/';
      preLoaderRoute: typeof CorporaCorpusIdTextIdIndexRouteImport;
      parentRoute: typeof CorporaCorpusIdTextIdRouteRoute;
    };
    '/corpora/$corpusId/$textId/plants': {
      id: '/corpora/$corpusId/$textId/plants';
      path: '/plants';
      fullPath: '/corpora/$corpusId/$textId/plants';
      preLoaderRoute: typeof CorporaCorpusIdTextIdPlantsRouteImport;
      parentRoute: typeof CorporaCorpusIdTextIdRouteRoute;
    };
    '/corpora/$corpusId/$textId/fulltext': {
      id: '/corpora/$corpusId/$textId/fulltext';
      path: '/fulltext';
      fullPath: '/corpora/$corpusId/$textId/fulltext';
      preLoaderRoute: typeof CorporaCorpusIdTextIdFulltextRouteImport;
      parentRoute: typeof CorporaCorpusIdTextIdRouteRoute;
    };
    '/corpora/$corpusId/$textId/entities': {
      id: '/corpora/$corpusId/$textId/entities';
      path: '/entities';
      fullPath: '/corpora/$corpusId/$textId/entities';
      preLoaderRoute: typeof CorporaCorpusIdTextIdEntitiesRouteImport;
      parentRoute: typeof CorporaCorpusIdTextIdRouteRoute;
    };
    '/corpora/$corpusId/$textId/animals': {
      id: '/corpora/$corpusId/$textId/animals';
      path: '/animals';
      fullPath: '/corpora/$corpusId/$textId/animals';
      preLoaderRoute: typeof CorporaCorpusIdTextIdAnimalsRouteImport;
      parentRoute: typeof CorporaCorpusIdTextIdRouteRoute;
    };
  }
}

interface CorporaCorpusIdTextIdRouteRouteChildren {
  CorporaCorpusIdTextIdAnimalsRoute: typeof CorporaCorpusIdTextIdAnimalsRoute;
  CorporaCorpusIdTextIdEntitiesRoute: typeof CorporaCorpusIdTextIdEntitiesRoute;
  CorporaCorpusIdTextIdFulltextRoute: typeof CorporaCorpusIdTextIdFulltextRoute;
  CorporaCorpusIdTextIdPlantsRoute: typeof CorporaCorpusIdTextIdPlantsRoute;
  CorporaCorpusIdTextIdIndexRoute: typeof CorporaCorpusIdTextIdIndexRoute;
}

const CorporaCorpusIdTextIdRouteRouteChildren: CorporaCorpusIdTextIdRouteRouteChildren =
  {
    CorporaCorpusIdTextIdAnimalsRoute: CorporaCorpusIdTextIdAnimalsRoute,
    CorporaCorpusIdTextIdEntitiesRoute: CorporaCorpusIdTextIdEntitiesRoute,
    CorporaCorpusIdTextIdFulltextRoute: CorporaCorpusIdTextIdFulltextRoute,
    CorporaCorpusIdTextIdPlantsRoute: CorporaCorpusIdTextIdPlantsRoute,
    CorporaCorpusIdTextIdIndexRoute: CorporaCorpusIdTextIdIndexRoute,
  };

const CorporaCorpusIdTextIdRouteRouteWithChildren =
  CorporaCorpusIdTextIdRouteRoute._addFileChildren(
    CorporaCorpusIdTextIdRouteRouteChildren
  );

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocIdRoute: DocIdRoute,
  DocApiRoute: DocApiRoute,
  CorporaIndexRoute: CorporaIndexRoute,
  CorporaCorpusIdTextIdRouteRoute: CorporaCorpusIdTextIdRouteRouteWithChildren,
  CorporaCorpusIdIndexRoute: CorporaCorpusIdIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
